from typing import Dict

CARDS_PER_PLAYER = 7
BASE_TRADING_COST = 2
DISCOUNTED_TRADING_COST = 1
MAXIMUM_TRADING_RESOURCES = 2
DISCARD_CARD_VALUE = 3

AGE_MILITARY_TOKENS: Dict[int, int] = {1: 1, 2: 3, 3: 5}
MILITARY_DEFEAT_TOKEN = -1
